# Generated by Django 6.0.2 on 2026-02-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_post_author_alter_post_categories_and_more"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="tags",
                to="tags.tags",
                verbose_name="Тэги",
            ),
        ),
    ]
