# Generated by Django 6.0.2 on 2026-02-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_alter_post_tags"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="tags.tags", verbose_name="Тэги"
            ),
        ),
    ]
